version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tutor-platform-postgres
    environment:
      POSTGRES_DB: tutor_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tutor-network

  redis:
    image: redis:7-alpine
    container_name: tutor-platform-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tutor-network

  minio:
    image: minio/minio:latest
    container_name: tutor-platform-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - tutor-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tutor-platform-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - MINIO_ENDPOINT=minio
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - tutor-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  tutor-network:
    driver: bridge

